name: Semver Tag
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Cargo Semver Update
        id: update
        uses: lemonxah/cargo_semver_update@v0.0.5
      
      - name: Commit file
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          files: |
            Cargo.toml
          commit-message: Updating Cargo semver version to ${{ steps.update.outputs.new_version }}
        
      - name: Commit tagger
        uses: tvdias/github-tagger@v0.0.2
        with:
          tag: ${{ steps.update.outputs.new_version_with_v }}
          
