name: Semver Tag
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cargo Semver Update and Tag
        uses: lemonxah/cargo_semver_update_and_tag@v0.0.10
        with:
          # GITHUB_TOKEN
          GITHUB_TOKEN: ${{ github.token }}
