# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Cargo Semver Update
        id: update
        # You may pin to the exact commit or the version.
        # uses: lemonxah/cargo_semver_update@3a56fc1dfb9e12127ff3395ba8456a6c304d8cad
        uses: lemonxah/cargo_semver_update@v0.0.5
      
      - name: Security work arround
        run: git config --global --add safe.directory /github/workspace
      
      - name: Commit and Push Branch
        # You may pin to the exact commit or the version.
        # uses: dsayling/commit-branch-check-action@bf76e20ce664016307431ce48b360f05ba7ae1ed
        uses: dsayling/commit-branch-check-action@v0.1.0
        with:
          # Github Token with write permissions
          github-token: ${{ github.token }}
          # Branch to push to after commit
          commit-message: "Updated Cargo.toml semver version to $ {{ steps.update.outputs.new_version }}"
          # Specific files to add before the commit.
          files: Cargo.toml

      - name: Commit tagger
        # You may pin to the exact commit or the version.
        # uses: tvdias/github-tagger@ed7350546e3e503b5e942dffd65bc8751a95e49d
        uses: tvdias/github-tagger@v0.0.2
        with:
          tag: ${{ steps.update.outputs.new_version_with_v }}
          
